### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by TrevorCEH** [hackthedev/teardrop#6]
please, add create  readme.txt /  warning message  in every Drive and sub directories  for send message.

If you mind can you make it dotnet 4 compitable.I believe it will works with my old windows 7 laptop to my brand new windows 10 desktop.

And Thanks for this reaserch project

**Comment by hackthedev** [comment]
As stated in issue #3 , this feature is about to be added. Although we mentioned an html file, a txt file can be used too. I will implement both of them tomorrow, if possible, and fix the issue you're having in issue #5

**Comment by TrevorCEH** [comment]
Thank you so much for your Quick response.

**Comment by hackthedev** [comment]
You're welcome. I'll message you when i've finished the new update
