### ISSUE TITLE
how to use,help

### ISSUE THREAD

**Issue by bennetho** [hackthedev/teardrop#8]
could someone please explain how to use it please

**Comment by hackthedev** [comment]
Hi.

What do you need help with? How familiar are you with visual studio and programming in c#?

**Comment by bennetho** [comment]
I want to know how to use it. I know abit of visual studio but I don’t know programming in c

**Comment by hackthedev** [comment]
Okay the problem is its "required" to understand how c# works and your IDE, Visual Studio. I'll make a video tutorial on how to use it because thats easier than explaining with plain words.

Its like explaining a joke. i woudnt be that good anymore

**Comment by bennetho** [comment]
👍🏽
