### ISSUE TITLE
Cannot encrypt on Windows 10 21H2

### ISSUE THREAD

**Issue by Abyss-W4tcher** [hackthedev/teardrop#9]
**Describe the bug**
Program doesn't encrypt anything.

**To Reproduce**
I download the repo zip, and put it in my VM with VS Studio. I open the project, and modify the config (only the name and I also change the theme). Microsoft defender is disabled too.

**Expected behavior**
I expect the program to start encrypting all the files.

**Screenshots**
![image](https://user-images.githubusercontent.com/82021419/194088904-34845661-280d-463a-bd80-3eda6ef5d36b.png)

Sorry it's in French, this means "Access denied". All the paths are "Musics", "Documents" etc. Basically, nothing is encrypted.

Could you help me face this problem ? I leave really all by default in VS code (except config), and generate the .exe. 

Thanks !

**Comment by hackthedev** [comment]
Thank you for reporting this issue :)

Did the program run as administrator and if not could you try again with admin privileges? Also its normal for some paths to fail but its strange if all of them fail. 

Did you try accessing these paths within the windows exporer?

**Comment by Abyss-W4tcher** [comment]
> Thank you for reporting this issue :)
> 
> Did the program run as administrator and if not could you try again with admin privileges? Also its normal for some paths to fail but its strange if all of them fail.
> 
> Did you try accessing these paths within the windows exporer?

I already tried to run it as Admin, but I will check again today ! It is a template VM, I just have a test file on my Desktop to see if it encrypts.

I guess those paths may be empty, now that you say it. But the files on my desktop aren't encrypted at all...

**Comment by Abyss-W4tcher** [comment]
I ran it again with admin mode, but I still have the problem :/

**Comment by hackthedev** [comment]
Im using Windows 10 Build 19044.
I will investigate in that issue

**Comment by Abyss-W4tcher** [comment]
Weird, I'm gonna rebuild a VM in english this time, I do not see why this would fix the problem but it's worth giving a try.

**Comment by Abyss-W4tcher** [comment]
Hi again, just tried with version 2.2.2 of your program, and the file on my desktop is encrypted !

I may not have configured the latest version correctly, but to be honest, a video tutorial for a simple setup lacks I think. 

However, I guess I'll stick with this version, as I need it just for demo purposes !

**Comment by hackthedev** [comment]
Oh yeah i was already thinking of making such a video but sadly i just have a lot of other stuff to do rn but i try my best to always come back to this. I plan to make other applications such as a Remote Administration Tool as well.
